before_install:
  - gem install bundler
  - git submodule update --init --recursive

rvm:
  - 2.2.2 # NOTE: 2.2.1 or lower aren't supported by activesupport 5.0, CI isn't needed for such legacy versions.
  - 2.2.6
  - 2.3.3
  - 2.4.1

env:
  - OPENSSL_VERSION=openssl-1.0.2
  - OPENSSL_VERSION=openssl-1.0.1
  - OPENSSL_VERSION=openssl-1.0.2
  - OPENSSL_VERSION=openssl-1.1.0
  - OPENSSL_VERSION=libressl-2.4
  - OPENSSL_VERSION=libressl-2.5
  - OPENSSL_VERSION=libressl-2.6

jdk:
  - oraclejdk8
